#!/bin/bash

# Compiles all .java files under the current directory to the specified directory.
# author: Jae Park

R="\e[0m"
B="\e[1m"

RED="\e[31m"
YELLOW="\e[33m"
GREEN="\e[32m"

usage() {
    cat << EOF
sjc by Jae Park
--------------------------------------------------
Usage: $(basename -- $0) sourceDir outputDir
       $(basename -- $0) -e outputDir mainClass
--------------------------------------------------
For more info, visit https://github.com/JP1128/sjc
EOF
}

info() {
    INFO="$B$GREEN[INFO]$R"
    printf "$INFO    $1\n"
}

warning() {
    WARNING="$B$YELLOW[WARNING]$R"
    printf "$WARNING $1\n"
}

error() {
    ERROR="$B$RED[ERROR]$R"
    printf "$ERROR   $1\n"
}

if [ $# -lt 2 ] || [ $# -gt 3 ]; then
    usage
    exit 0
fi

while getopts 'e' opt; do
    case "${opt}" in
        e)
            error "WIP"
            exit 0         
    esac
done

SOURCEDIR=$1
OUTPUTDIR=$2

info "Source directory: $SOURCEDIR"
info "Output directory: $OUTPUTDIR"

if [ ! -e $SOURCEDIR ]; then
    error "$SOURCEDIR does not exist"
    exit 2
elif [ ! -e $OUTPUTDIR ]; then
    warning "$OUTPUTDIR does not exist"
    info "Creating $OUTPUTDIR..."
    mkdir $OUTPUTDIR
    if [ ! -e $OUTPUTDIR ]; then
        error "Unable to create $OUTPUTDIR"
        exit 3
    fi
    info "Successfully created $OUTPUTDIR"
fi

info "Creating temporary text file for source code paths"
TEMP=$(mktemp /tmp/sjcXXXXXXX --suffix=.txt)

if [ ! -e $TEMP ]; then
    error "Unable to create $TEMP"
    exit 4
fi

trap "{ rm -f $TEMP; }" EXIT

info "Successfully created $TEMP"    

info "Writing source code paths to $TEMP"
find $SOURCEDIR -name "*.java" > $TEMP
info "Compiling..."

ERR=$( { javac -d $OUTPUTDIR "@$TEMP"; } 2>&1 )
CODE="$?"
if [ -n "$ERR" ]; then
    error "Compile-time Error detected"    
    IFS=''
    echo "$ERR" |
        while read -r line
        do
            error "$line"
        done
    
    read -p "$(info "Remove $OUTPUTDIR? [y|n]: ")" response

    if [ $response == "y" ]; then
        rm -rf $OUTPUTDIR
        info "Removed $OUTPUTDIR"
    fi
    
    exit 5
fi

info "Successfully compiled"
info "Ready for execution"
