#!/bin/bash

# Compiles all .java files under the current directory to the specified directory.
# author: Jae Park

R=$(tput sgr0)
B=$(tput bold)

RED="\e[31m"
YELLOW="\e[33m"
GREEN="\e[32m"

usage() {
    cat << EOF
${B}sjc by Jae Park${R}
--------------------------------------------------
Usage: $(basename -- $0) sourceDir outputDir
       $(basename -- $0) -e outputDir mainClass
       $(basename -- $0) -c directory
--------------------------------------------------
For more info, visit https://github.com/JP1128/sjc
EOF
    exit 1
}

info() {
    INFO="$B$GREEN[INFO]$R"
    printf "$INFO    $1\n"
}

warning() {
    WARNING="$B$YELLOW[WARNING]$R"
    printf "$WARNING $1\n"
}

error() {
    ERROR="$B$RED[ERROR]$R"
    printf "$ERROR   $1\n"
}

[ $# -eq 0 ] && usage
[ $1 == "-h" ] && usage


# execution

if [ $1 == "-e" ]; then

    [ ! $# -eq 3 ] && usage

    CLASSDIR=$2
    MAINCLASS=$(find "$CLASSDIR" -type f -name "$3.class")
    
    if [ ! -e $MAINCLASS ]; then
        error "Could not locate $3.class"
        error "Exiting..."
        exit 6
    fi

    DIRPATH=$(echo "$(dirname -- $MAINCLASS)" | sed "s/$2//")
    PATH_TO_CLASS=$(echo "$DIRPATH/$3" | sed 's/\//./' | sed 's/^.//')
    
    java -cp $CLASSDIR $PATH_TO_CLASS
    exit 0
fi

if [ $1 = "-c" ]; then
    
    [ ! $# -eq 2 ] && usage

    BINDIR=$2
    info "Finding $BINDIR..."

    if [ ! -e $BINDIR ]; then
        error "$BINDIR does not exist"
        error "Exiting..."
        exit 7
    fi

    info "Cleaning $BINDIR..."
    rm -r "$BINDIR"/*
    if [ ! $? -eq 0 ]; then
        error "Unknown error while cleaning $BINDIR"
        error "Exiting..."
        exit 8
    fi
    
    info "Successfully cleaned $BINDIR"
    exit 0
fi


# compiling

[ ! $# -eq 2 ] && usage

SOURCEDIR=$1
OUTPUTDIR=$2

info "Source directory: $SOURCEDIR"
info "Output directory: $OUTPUTDIR"

if [ ! -e $SOURCEDIR ]; then
    error "$SOURCEDIR does not exist"
    error "Exiting..."
    exit 2
elif [ ! -e $OUTPUTDIR ]; then
    warning "$OUTPUTDIR does not exist"
    info "Creating $OUTPUTDIR..."
    mkdir $OUTPUTDIR
    if [ ! -e $OUTPUTDIR ]; then
        error "Unable to create $OUTPUTDIR"
        error "Exiting..."
        exit 3
    fi
    info "Successfully created $OUTPUTDIR"
fi

info "Creating temporary text file for source code paths"
TEMP=$(mktemp /tmp/sjcXXXXXXX --suffix=.txt)

if [ ! -e $TEMP ]; then
    error "Unable to create $TEMP"
    error "Exiting..."
    exit 4
fi

trap "{ rm -f $TEMP; }" EXIT

info "Successfully created $TEMP"    

info "Writing source code paths to $TEMP"
find $SOURCEDIR -name "*.java" > $TEMP
info "Compiling..."

ERR=$( { javac -d $OUTPUTDIR @"$TEMP"; } 2>&1 )

if [ -n "$ERR" ]; then
    error "Compile-time Error detected"    
    IFS=''
    echo "$ERR" |
        while read -r line
        do
            error "$line"
        done
    
    read -p "$(info "Remove $OUTPUTDIR? [y|n]: ")" response

    if [ $response == "y" ]; then
        rm -rf $OUTPUTDIR
        info "Removed $OUTPUTDIR"
    fi

    error "Exiting..."
    exit 5
fi

info "Successfully compiled"
info "Ready for execution"
